### ISSUE TITLE
acpi.h : Necessary header file not included

### ISSUE THREAD

**Issue by healytpk** [frantony/barebox#2]
"acpi.h" can cause a build failure because it doesn't include the necessary header file for "memcmp".

I'm not sure if this is by design (i.e. I'm not sure if you are supposed to include "common.h" before all other headers).

**Comment by frantony** [comment]
Fixed in https://github.com/frantony/barebox/commit/298c3ffe3afb0d3d1b538b2ccb95f44efa37f4ce

See also https://github.com/saschahauer/barebox/issues/7
